/** This code is licensed for Maulana Hilmi Arkan
 * All right reserved
 * package Tugas;
 *
 * /**
 *
 * @author HP ZBOOK 15
 */
public class TampilanKalkulator extends javax.swing.JFrame {
    String angka;
    double jumlah,angka1,angka2;
    int pilih;

    /**
     * Creates new form TampilanKalkulator
     */
    public TampilanKalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Hapus = new javax.swing.JButton();
        Lima = new javax.swing.JButton();
        Bagi = new javax.swing.JButton();
        Satu = new javax.swing.JButton();
        Dua = new javax.swing.JButton();
        Tiga = new javax.swing.JButton();
        Kali = new javax.swing.JButton();
        Enam = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        Tujuh = new javax.swing.JButton();
        Delapan = new javax.swing.JButton();
        Sembilan = new javax.swing.JButton();
        Kurang = new javax.swing.JButton();
        Nol = new javax.swing.JButton();
        Koma = new javax.swing.JButton();
        SamaDengan = new javax.swing.JButton();
        Empat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 200));

        Hapus.setText("C");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 230, 60));

        Lima.setText("5");
        Lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimaActionPerformed(evt);
            }
        });
        getContentPane().add(Lima, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 70, 60));

        Bagi.setText("/");
        Bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagiActionPerformed(evt);
            }
        });
        getContentPane().add(Bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 70, 60));

        Satu.setText("1");
        Satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatuActionPerformed(evt);
            }
        });
        getContentPane().add(Satu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, 60));

        Dua.setText("2");
        Dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuaActionPerformed(evt);
            }
        });
        getContentPane().add(Dua, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 70, 60));

        Tiga.setText("3");
        Tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TigaActionPerformed(evt);
            }
        });
        getContentPane().add(Tiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 70, 60));

        Kali.setText("*");
        Kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 70, 60));

        Enam.setText("6");
        Enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnamActionPerformed(evt);
            }
        });
        getContentPane().add(Enam, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 70, 60));

        Tambah.setText("+");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        getContentPane().add(Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 70, 60));

        Tujuh.setText("7");
        Tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuhActionPerformed(evt);
            }
        });
        getContentPane().add(Tujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, 60));

        Delapan.setText("8");
        Delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelapanActionPerformed(evt);
            }
        });
        getContentPane().add(Delapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 70, 60));

        Sembilan.setText("9");
        Sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SembilanActionPerformed(evt);
            }
        });
        getContentPane().add(Sembilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 70, 60));

        Kurang.setText("-");
        Kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KurangActionPerformed(evt);
            }
        });
        getContentPane().add(Kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 70, 60));

        Nol.setText("0");
        Nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NolActionPerformed(evt);
            }
        });
        getContentPane().add(Nol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 150, 60));

        Koma.setText(",");
        Koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KomaActionPerformed(evt);
            }
        });
        getContentPane().add(Koma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 70, 60));

        SamaDengan.setText("=");
        SamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamaDenganActionPerformed(evt);
            }
        });
        getContentPane().add(SamaDengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 70, 60));

        Empat.setText("4");
        Empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpatActionPerformed(evt);
            }
        });
        getContentPane().add(Empat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 70, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuActionPerformed
       // TODO add your handling code here:
       angka += "x";
       display.setText(angka);
    }//GEN-LAST:event_SatuActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        display.setText("");
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka="";
    }//GEN-LAST:event_HapusActionPerformed

    private void KaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("*");
        angka="";
        pilih=3;
    }//GEN-LAST:event_KaliActionPerformed

    private void DuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuaActionPerformed
        // TODO add your handling code here:
        angka += "x";
        display.setText(angka);
    }//GEN-LAST:event_DuaActionPerformed

    private void TigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TigaActionPerformed
        // TODO add your handling code here:
        angka += "x";
        display.setText(angka);
    }//GEN-LAST:event_TigaActionPerformed

    private void EmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpatActionPerformed
        // TODO add your handling code here:
        angka += "x";
        display.setText(angka);
    }//GEN-LAST:event_EmpatActionPerformed

    private void LimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimaActionPerformed
        // TODO add your handling code here:
        angka += "x";
        display.setText(angka);
    }//GEN-LAST:event_LimaActionPerformed

    private void EnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnamActionPerformed
        // TODO add your handling code here:
        angka += "x";
        display.setText(angka);
    }//GEN-LAST:event_EnamActionPerformed

    private void TujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuhActionPerformed
        // TODO add your handling code here:
        angka += "x";
        display.setText(angka);
    }//GEN-LAST:event_TujuhActionPerformed

    private void DelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelapanActionPerformed
        // TODO add your handling code here:
        angka += "x";
        display.setText(angka);
    }//GEN-LAST:event_DelapanActionPerformed

    private void SembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SembilanActionPerformed
        // TODO add your handling code here:
        angka += "x";
        display.setText(angka);
    }//GEN-LAST:event_SembilanActionPerformed

    private void NolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NolActionPerformed
        // TODO add your handling code here:
        angka += "x";
        display.setText(angka);
    }//GEN-LAST:event_NolActionPerformed

    private void KomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KomaActionPerformed
        // TODO add your handling code here:
        angka += ".";
        display.setText(angka);
    }//GEN-LAST:event_KomaActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("+");
        angka="";
        pilih=1;
    }//GEN-LAST:event_TambahActionPerformed

    private void KurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KurangActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_KurangActionPerformed

    private void BagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("/");
        angka="";
        pilih=4;
    }//GEN-LAST:event_BagiActionPerformed

    private void SamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamaDenganActionPerformed
        // TODO add your handling code here:
            switch(pilih){
        case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
            default:
            break;
} 
    }//GEN-LAST:event_SamaDenganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanKalkulator().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagi;
    private javax.swing.JButton Delapan;
    private javax.swing.JButton Dua;
    private javax.swing.JButton Empat;
    private javax.swing.JButton Enam;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Kali;
    private javax.swing.JButton Koma;
    private javax.swing.JButton Kurang;
    private javax.swing.JButton Lima;
    private javax.swing.JButton Nol;
    private javax.swing.JButton SamaDengan;
    private javax.swing.JButton Satu;
    private javax.swing.JButton Sembilan;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Tiga;
    private javax.swing.JButton Tujuh;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
